"""empty message

Revision ID: 4ec43438a776
Revises: beed8da02afb
Create Date: 2024-04-13 14:32:15.372023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec43438a776'
down_revision = 'beed8da02afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requ',
    sa.Column('r_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('r_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requ')
    # ### end Alembic commands ###
