"""empty message

Revision ID: 5e3409c2c0ca
Revises: bc74a7bbe482
Create Date: 2024-04-14 11:55:12.157638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3409c2c0ca'
down_revision = 'bc74a7bbe482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('b_title', sa.String(length=20), nullable=False),
    sa.Column('b_author', sa.String(length=20), nullable=False),
    sa.Column('b_content', sa.String(length=500), nullable=False),
    sa.Column('sec_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sec_id'], ['section.s_id'], ),
    sa.PrimaryKeyConstraint('b_id')
    )
    op.create_table('access',
    sa.Column('a_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('b_issued_date', sa.DateTime(), nullable=False),
    sa.Column('b_return_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.b_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('a_id')
    )
    op.drop_table('books')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['b_id'])
        batch_op.drop_column('permission')

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('u_email',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('u_email',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('duration')

    op.create_table('books',
    sa.Column('b_id', sa.INTEGER(), nullable=False),
    sa.Column('b_title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('b_author', sa.VARCHAR(length=20), nullable=False),
    sa.Column('b_content', sa.VARCHAR(length=500), nullable=False),
    sa.Column('b_issued_date', sa.DATETIME(), nullable=False),
    sa.Column('b_return_date', sa.DATETIME(), nullable=False),
    sa.Column('sec_id', sa.INTEGER(), nullable=False),
    sa.Column('b_rating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sec_id'], ['section.s_id'], ),
    sa.PrimaryKeyConstraint('b_id')
    )
    op.drop_table('access')
    op.drop_table('book')
    # ### end Alembic commands ###
